// Mocks generated by Mockito 5.4.4 from annotations
// in cruise_connect/test/route/route_generation_mock_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:cruise_connect/data/services/route_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RouteEdgeInvoker].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouteEdgeInvoker extends _i1.Mock implements _i3.RouteEdgeInvoker {
  MockRouteEdgeInvoker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<dynamic> invoke(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(#invoke, [body]),
        returnValue: _i2.Future<dynamic>.value(),
        returnValueForMissingStub: _i2.Future<dynamic>.value(),
      ) as _i2.Future<dynamic>);
}
