// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArsBfXT__RU7ZMZPDljH3TLGdEuHcSYKc',
    appId: '1:643677007260:web:801238d0799c079bb76c59',
    messagingSenderId: '643677007260',
    projectId: 'cruise-connect-a1772',
    authDomain: 'cruise-connect-a1772.firebaseapp.com',
    storageBucket: 'cruise-connect-a1772.firebasestorage.app',
    measurementId: 'G-PJXDTZC5F3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnG4JDcppSoWYZd35Wdvf8ESGSeB18vJs',
    appId: '1:643677007260:ios:f1c5d37b5fca499bb76c59',
    messagingSenderId: '643677007260',
    projectId: 'cruise-connect-a1772',
    storageBucket: 'cruise-connect-a1772.firebasestorage.app',
    iosBundleId: 'com.example.cruiseConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnG4JDcppSoWYZd35Wdvf8ESGSeB18vJs',
    appId: '1:643677007260:ios:f1c5d37b5fca499bb76c59',
    messagingSenderId: '643677007260',
    projectId: 'cruise-connect-a1772',
    storageBucket: 'cruise-connect-a1772.firebasestorage.app',
    iosBundleId: 'com.example.cruiseConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArsBfXT__RU7ZMZPDljH3TLGdEuHcSYKc',
    appId: '1:643677007260:web:dcb809f60a257243b76c59',
    messagingSenderId: '643677007260',
    projectId: 'cruise-connect-a1772',
    authDomain: 'cruise-connect-a1772.firebaseapp.com',
    storageBucket: 'cruise-connect-a1772.firebasestorage.app',
    measurementId: 'G-80TGNX6GQ6',
  );

}